### ISSUE TITLE
Parsing error in function redirection

### ISSUE THREAD

**Issue by SirCmpwn** [emersion/mrsh#55] opened 2018-11-03 14:37 UTC
```sh
#!/bin/sh
file=example_1

example() {
	echo hello world
} > $file

example
file=example_2
example
```

<details>
<summary>Show AST</summary>
<pre>
~/s/m/build > ./mrsh -n test.sh
program
program
└─command_list ─ pipeline
  └─simple_command
    └─assignment
      ├─name file
      └─value ─ word_string [2:6 → 2:15] example_1
program
program
├─command_list ─ pipeline
│ └─function_definition example ─ brace_group
│   └─command_list ─ pipeline
│     └─simple_command
│       ├─name ─ word_string [5:2 → 5:6] echo
│       ├─argument 1 ─ word_string [5:7 → 5:12] hello
│       └─argument 2 ─ word_string [5:13 → 5:18] world
└─command_list ─ pipeline
  └─simple_command
    └─io_redirect
      ├─io_number -1
      ├─op >
      └─name ─ word_parameter
        └─name file
program
program
└─command_list ─ pipeline
  └─simple_command
    └─name ─ word_string [8:1 → 8:8] example
program
└─command_list ─ pipeline
  └─simple_command
    └─assignment
      ├─name file
      └─value ─ word_string [9:6 → 9:15] example_2
program
└─command_list ─ pipeline
  └─simple_command
    └─name ─ word_string [10:1 → 10:8] example
</pre>
</details>

Expected: the redirection should be a part of the function node. It will need to be stored with the function and evaluated each time the function is called.

**Comment by emersion** [comment] 2018-11-03 14:38
Duplicate of https://github.com/emersion/mrsh/issues/30

**Comment by SirCmpwn** [comment] 2018-11-03 14:38
rip

**Closed by emersion** 2018-11-03 14:38 UTC
