### ISSUE TITLE
PS1 expansion

### ISSUE THREAD

**Issue by Hummer12007** [emersion/mrsh#88] opened 2019-02-21 19:20 UTC
PS1 expansion for non-alphanumeric PS1s (like "$ ") does not work (`"test $ test" gets expanded to `"test "`).
It currently hits https://github.com/emersion/mrsh/blob/master/ast.c#L609

We might need to run word jobs on the PS1.

**Comment by emersion** [comment] 2019-02-28 16:21
It seems we already run word jobs for PS1.

How to reproduce this issue? Tried `PS1='test $ test'`, this correctly prints `test test`.

**Comment by Hummer12007** [comment] 2019-02-28 23:04
It should print 'test $ test' though

**Comment by emersion** [comment] 2019-03-01 07:56
The `$` issue is a duplicate of https://github.com/emersion/mrsh/issues/13

The `>` issue is probably mrsh trying to recognize a redirection operator.

**Comment by emersion** [comment] 2019-12-13 15:21
PS1 is only subject to parameter expansion. Right now we use `mrsh_parse_word`, which also recognizes operators and quotes, that's not appropriate. We should probably copy-paste `double_quotes` and remove all the stuff we don't need.

**Closed** 2019-12-13 15:52 UTC
